export const data1 = [
    {
      title: "Banking",
      description:
        "From financial fraud control to complete banking automation solution using Artificial intelligence(AI) and Machine Learning(ML) technology. Our MLops framework will give you unprecedented technology advantage for next few decades.",
      images: "/images/banking.jpg",
    },
    {
      title: "Insurance",
      description:
        "With our MLops framework, insurance's crucial predictive Machine Learning and dynamic premium pricing will setup new industry standards. Hence huge time and cost savings.",
      images: "/images/insurance.jpg",
    },
    {
      title: "Capital Markets",
      description:
        "From algo trading to legal documents processing automation, our MLops framework will completely optimize majority of business processes in capital markets",
      images: "/images/stocks.jpg",
    },
   
  ];

  export const data2 = [
    {
      title: "Retail",
      description:
        "Creating unforgettable customer experiences through our MLops framework by in-depth customer insights to transforming entire supply-chain and personalizations through voice chatbot. ",
      images: "/images/retail.jpg",
    },
    {
      title: "Education",
      description:
        "Our MLops framework enable teachers to have AI assistants that will almost replace text books and non creative ways of learning experiences.",
      images: "/images/edu.jpg",
    },
    {
      title: "Manufacturing",
      description:
        "Manage your manufacturing units better through dynamic demand and supply using power of Artificial Intelligence(AI) technology and our MLops framework. ",
      images: "/images/manu.jpg",
    },
   
  ];

  export const data3 = [
    {
      title: "Governance",
      description:
        "Make better strategies for people that will improve their lives for decades through power of Artificial Intelligence(AI) technology and our MLops framework. ",
      images: "/images/gov.jpg",
    },
    {
      title: "Healthcare",
      description:
        "Plan and operate your health care services better to give safe and reliable medical facilities for every citizens using Artificial Intelligence(AI) and our MLops framework. ",
      images: "/images/health.jpg",
    },
    {
      title: "Pharmaceuticals",
      description:
        "New drugs discovery and vaccines development can never be so fast, thanks to Artificial Intelligence(AI) technology and our MLops framework. ",
      images: "/images/pharma.jpg",
    },
   
  ];

  export const data4 = [
    {
      title: "Media and Entertainment",
      description:
        "Detecting fake news or copyrighted content generated by AI technology, everything will be changed in this industry and thankfully our MLops framework will handle it. ",
      images: "/images/media.jpg",
    },
    {
      title: "Communications",
      description:
        "AI  with our MLops framework is used to optimize and manage 5G networks to improve connectivity in order to meet the increasing demand for high-speed, reliable communication services.",
      images: "/images/pexels-pixabay-373543.jpg",
    },
    {
      title: "Energy",
      description:
        "AI with our MLops framework will enable smart grid and carbon emission reduction system by optimizing processes along with cleaner energy sources, reducing the overall carbon footprint of the energy industry",
      images: "/images/energy.jpg",
    },
]
    export const data5 = [
        {
          title: "Defense",
          description:
            "AI and MLops framework can lead to autonomous systems, ground vehicles, and underwater vehicles that can perform various tasks, such as surveillance, reconnaissance, and even combat operations, without human intervention.",
          images: "/images/wepon.jpg",
        },
        {
          title: "High Tech",
          description:
            "Collaborative robots, or cobots, are employed in high-tech industries to work alongside human workers. This enhances productivity and efficiency by combining human creativity with machine precision. Our MLops framework is ready for it.",
          images: "/images/pexels-bruno-bueno-3907022.jpg",
        },
        {
          title: "Aviation",
          description:
            "AI with MLops can assist in air traffic control systems to manage the increasing volume of air traffic. Automated systems can analyze data in real-time to predict and mitigate congestion issues, reducing delays and improving overall airspace utilization. AI can also identify potential safety risks and recommend preventive measures.",
          images: "/images/avi.jpg",
        },]
        export const data6 = [
            {
              title: "Space",
              description:
                "Space missions generate vast amounts of data. Our MLops can be used to analyze and interpret this data quickly and accurately. ML algorithms can identify patterns, anomalies, and relevant information within massive datasets, helping scientists and engineers make informed decisions quickly and efficiently.",
              images: "/images/space.jpg",
            },
            {
              title: "Logistics",
              description:
                "Our MLops framework helps logistics providers in identifying and mitigating risks within the supply chain, such as disruptions due to natural disasters, geopolitical events, or other unforeseen circumstances. Predictive analytics can assist in developing contingency plans to minimize the impact of these risks.",
              images: "/images/logistics.jpg",
            },
            {
              title: "Tourism",
              description:
                "AI-powered language translation services using our MLops framework assist travelers in overcoming language barriers and enable tourists to communicate more effectively in foreign countries.AI algorithms also analyze vast amounts of data, including user preferences and behaviors to provide personalized recommendations.",
              images: "/images/tour.jpg",
            },
        ];